package index.lemmaPlain;


import index.DocReader;
import index.IndexerException;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Iterator;


/**
 * Modern Hebrew document reader
 * Format generated by milaCorpora.GeneratePlainTextCorporaFromXml
 * @author HZ
 */
public class ModernHebrewLemmaTextDocReader extends LemmaTextDocReader
{
	private static final String SPACE = "\\s+";
	private File[] corpusFiles;
	private int currId;
	private File currFile;
	private BufferedReader currReader;
	private String currPlainText;
	private String currSentText;
	private String currSentId;
	private String currSentPath;
	private String inputDir;
	private String currSource = null;
	private Iterator<String> termIter;

	/**
	 * @param dir folder containing files to read
	 * @throws IndexerException
	 */
	public ModernHebrewLemmaTextDocReader(File dir) throws IndexerException
	{
		super();
		if (dir == null || !dir.exists())
			throw new IndexerException("the directory is null or nonexistant");
		inputDir = dir.getAbsolutePath();
		corpusFiles = dir.listFiles();
		currId = 0;
		currFile = corpusFiles[currId];
		try {
			currReader = new BufferedReader(new FileReader(currFile));
		} catch (FileNotFoundException e) {
			throw new IndexerException("IOException: " + e.getMessage());
		}
	}
	
	/* (non-Javadoc)
	 * @see new_search.DocReader#next()
	 */
	
	public boolean next() throws IndexerException
	{
		String line;
		try {
			line = currReader.readLine();
			if (line == null) {
				currReader.close();
				currId++;
				if (currId < corpusFiles.length) {
			        currFile = corpusFiles[currId];
					currReader = new BufferedReader(new FileReader(currFile));
					line = currReader.readLine();
				}
				else
					return false;
			}
			String[] tokens = line.split("@@");
			currSentPath = tokens[0];
			currSentId = tokens[1];
			currSentText = tokens[2];
			currPlainText = tokens[3];
//			currSentText = currSentText.replaceAll("[\\x07\t\f\n-]", " ");
//			currSentText = currSentText.replaceAll("[^אבגדהלוזחטיכגמנסעפצקרשתץףךםןת\'\\s\"]", "");
			termIter =  Arrays.asList(currSentText.split(SPACE)).iterator();
			return true;
		} catch (IOException e) {
			throw new IndexerException("IOException: " + e.getMessage());
		}
	}

	/* (non-Javadoc)
	 * @see index.DocReader#docId()
	 */
	
	public String docId() throws IndexerException
	{
		return currSentPath;
	}

	/* (non-Javadoc)
	 * @see index.DocReader#doc()
	 */
	
	public String doc()
	{
		return currSentText;
	}

	/* (non-Javadoc)
	 * @see index.DocReader#readToken()
	 */
	
	public String readToken() throws IndexerException
	{
		if (termIter == null)
			throw new IndexerException("you must call next() before calling readToken()");
		
		return termIter.hasNext() ? termIter.next() : null;
	}

	/* (non-Javadoc)
	 * @see java.io.Reader#read(char[], int, int)
	 */
	public int read(char[] cbuf, int off, int len) throws IOException
	{
		return currReader.read(cbuf, off, len);
	}

	/* (non-Javadoc)
	 * @see java.io.Reader#close()
	 */
	public void close() throws IOException
	{
		if (currReader != null)
			currReader.close();
	}

	/* (non-Javadoc)
	 * @see index.DocReader#sent()
	 */
	
	public String period() throws IndexerException {
		return currSentId;
	}

	/* (non-Javadoc)
	 * @see index.DocReader#source()
	 */
	
	public String source() throws IndexerException {
		// source name is the upper directory name
		currSource = getSourceName();
		currSource = currSource.replaceAll(".txt", "");
		return currSource;
	}
	
	
	public int length() throws IndexerException {
		// TODO Auto-generated method stub
		return currSentText.split(" ").length;
	}
	
	public String plain() throws IndexerException {
		return currPlainText;
	}
	
	//
	////////////////////////////////////////////////////////// PRIVATE /////////////////////////////////////////////
	//
	
	
	/**
	 * Gets the source folder
	 * @return String containing upper folder name to be used as a source name
	 */
	private String getSourceName() 
	{
		File p = currFile.getParentFile();
		File d = new File(inputDir);
		File temp = currFile;
		while(!p.equals(d)){
			temp = p;
			p = p.getParentFile();	
		}
		//here, temp is the upper folder of the given file
		String tempStr = temp.getName();
		return tempStr;
	}

	
}
	
